### ISSUE TITLE
Useless old state - unused

### ISSUE THREAD

**Issue by Thenkei** [Thenkei/UnderTheLimits#33]
The *value* state is unused. Can the component not render if I remove the setState (link below) ?

https://github.com/Thenkei/UnderTheLimits/blob/a7118c99879bbf901bb78c79e3fc2e656f60f738/client/src/UnderTheLimits.jsx#L44

**Comment by jeffladiray** [comment]
Not sure about the question.

Most of the time, you shouldn't care too much about re-rendering a component, since without ugly tricks (`this.forceUpdate()`, ...), a re-render can only be triggered if a component's state has changed. You can also define `static getDerivedStateFromProps(props, state)` to initiate state change using props change.

Does that answer your question ?

**Comment by Thenkei** [comment]
I was concern about letting a unused code that it might be used to re-render component when changing state. You're good my friend.

**Comment by Thenkei** [comment]
Close issue
