### ISSUE TITLE
Crash -Server

### ISSUE THREAD

**Issue by Thenkei** [Thenkei/UnderTheLimits#44]
A player got disconnected just before this call and server crashed.

https://github.com/Thenkei/UnderTheLimits/blob/59920f95f0d4087cbf7d8c69f889185f4b887200/server/index.js#L177

```
utl-server    | channel Salon4Jardin next round starting...
utl-server    | Player Sigmund  got disconnected from lobby
utl-server    | Player removed from channel
utl-server    | /server/index.js:181
utl-server    |         currentPlayer.answers = answers;
utl-server    |                               ^
utl-server    |
utl-server    | TypeError: Cannot set property 'answers' of undefined
utl-server    |     at Socket.client.on (/server/index.js:181:31)
utl-server    |     at Socket.emit (events.js:182:13)
utl-server    |     at /server/node_modules/socket.io/lib/socket.js:528:12
utl-server    |     at process._tickCallback (internal/process/next_tick.js:61:11)
utl-server    | [nodemon] app crashed - waiting for file changes before starting...
```

**Comment by Thenkei** [comment]
This senario can be remove if we allow deco/reco from playing channel. (so player is not removed from the channel thus this error shouldn't happen anymore..)

**Comment by jeffladiray** [comment]
Deco/reco based only on username wouldn't be great, since username can easily be "faked"

For now, we can handle basic auth with generated token saved in localstorage, but it will also be way harder to develop on the project, since multiple browser would be needed

Will look forward to find solution that match our needs
