### ISSUE TITLE
Reducer handling error

### ISSUE THREAD

**Issue by Thenkei** [Thenkei/UnderTheLimits#58]
We need to change **Socket server side API** in order to make the following **_wssFunctionType_** work.
### Reducer
https://github.com/Thenkei/UnderTheLimits/blob/283a957125c9b7bea3fbc59c2b41c8537feada4f/client/src/reducers/app.js#L80-L98

Another implementation:
``` javascript
export function wssCreatePlayer(wsCreatePlayerReq) { 
   return (dispatch) => { 
     dispatch(createPlayerRequest()); 
     createPlayer(wsCreatePlayerReq, (err, wsCreatePlayerRes) => { 
       if (wsCreatePlayerRes) {
         // eslint-disable-next-line prefer-destructuring 
         id = wsCreatePlayerRes.id; 
         dispatch(createPlayerSucess(wsCreatePlayerRes)); 
         retrurn;
       }
       dispatch(createPlayerFailure(error));
     }); 
   }; 
 } 
```

### Client API
https://github.com/Thenkei/UnderTheLimits/blob/283a957125c9b7bea3fbc59c2b41c8537feada4f/client/src/services/Api.js#L5-L8

Changes:
``` javascript
 function createPlayer(playerName, cb) { 
   global.socket.emit('createPlayer', playerName); 
   global.socket.on('playerCreated', lobbyResponse => cb(lobbyResponse.error, lobbyResponse.player)); 
 } 
```

### Server API
https://github.com/Thenkei/UnderTheLimits/blob/283a957125c9b7bea3fbc59c2b41c8537feada4f//server/src/lobby.js#L59

Becomes:
``` javascript
client.emit('playerCreated', { error: err.message });
```

So, we need to talk about this and also about the `RESQUEST -> FAILLURE | SUCCESS` system.

**Comment by jeffladiray** [comment]
Clearly handling server side error wasn't a part of my plan initialy, but just to make basic game play to work with reducers 😆 

Most of the `_REQUEST` / `_SUCCESS` on `.emit()` stuff is useless and should be removed (Since there is no request/reponse process when emitting only ?)
Also, I didn't review #57, so ... there might be more useless stuff 

All the server errors should be formatted the same way, so using `{ error: err.message }` seems fine to me!
In fact, all the response (error or success) from the server should have a proper serializer
